import {ALL_CRAFT_CITIES,BLACK_MARKET,DEFAULT_SETTINGS,SERVERS} from './constants.js';
import {buildPriceLookup,buildVolumeMap,fetchHistory,fetchPrices,loadCatalog} from './api.js';
import {batchMetrics,evaluateItem} from './engine.js';
import {fmtAge,fmtPct,fmtSilver,fmtVolume,humanizeId,itemIcon,itemTierLabel} from './format.js';
import {loadFavorites,loadOverrides,loadSettings,saveFavorites,saveOverrides,saveSettings} from './storage.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const state={settings:loadSettings(),favorites:loadFavorites(),overrides:loadOverrides(),catalog:[],catalogSource:'seed',results:[],tab:'scanner',selected:null,sort:['score','desc'],scanning:false,status:'Loading catalog…',error:'',updated:null};
const app=$('#app');
const save=(k,v)=>{state.settings={...state.settings,[k]:v};saveSettings(state.settings)};
const scenario=(r,focus=false)=>{const m=focus?r.modes.focus:r.modes.baseline,a=m.bestRoyal,b=m.caerleon;return !a?b:!b?a:a.profit>=b.profit?a:b};
const deployable=()=>Math.min(Number(state.settings.wallet||0),Number(state.settings.budget||state.settings.wallet||0));
const categories=()=>[...new Set(state.catalog.map(x=>x.category).filter(Boolean))].sort();
const candidateItems=()=>state.catalog.filter(x=>(state.settings.tier==='all'||+x.tier===+state.settings.tier)&&(!state.settings.enchants.length||state.settings.enchants.includes(+(x.enchantment||0)))&&(state.settings.category==='all'||x.category===state.settings.category));
const pass=r=>{const s=state.settings,x=scenario(r);return x&&x.profit>=+s.minProfit&&x.roi*100>=+s.minRoi&&(r.primary?.volume||0)>=+s.minVolume&&x.worstAge<=+s.freshnessHours&&(!s.affordableOnly||x.cashRequired*50<=deployable())};
const val=(r,k)=>({score:r.score,name:r.recipe.name||r.recipe.id,volume:r.primary?.volume||0,royal:r.modes.baseline.bestRoyal?.profit??-Infinity,caer:r.modes.baseline.caerleon?.profit??-Infinity,roi:scenario(r)?.roi??-Infinity,capital:(scenario(r)?.cashRequired??Infinity)*50,profit:(scenario(r)?.profit??-Infinity)*50,age:scenario(r)?.worstAge??Infinity}[k]??0);
function rows(){let a=state.results.filter(pass);if(state.tab==='favorites')a=a.filter(r=>state.favorites.has(r.recipe.id));if(state.tab==='movers')return a.sort((x,y)=>(y.primary?.volume||0)-(x.primary?.volume||0));const[k,d]=state.sort;return a.sort((x,y)=>(val(x,k)>val(y,k)?1:val(x,k)<val(y,k)?-1:0)*(d==='asc'?1:-1))}
function progress(t){state.status=t;const e=$('#scan-status');if(e)e.textContent=t}

async function scan(){if(state.scanning)return;state.scanning=true;state.error='';state.results=[];render();try{const items=candidateItems();if(!items.length)throw Error('No recipes match the current filters.');const products=items.map(x=>x.id),materials=items.flatMap(x=>x.variants.flatMap(v=>v.materials.map(m=>m.id)));progress(`Fetching ${products.length} Black Market quotes…`);const bm=await fetchPrices(state.settings.server,products,[BLACK_MARKET],(d,t)=>progress(`Black Market ${d}/${t} batches…`));progress('Fetching component markets…');const mats=await fetchPrices(state.settings.server,materials,ALL_CRAFT_CITIES,(d,t)=>progress(`Components ${d}/${t} batches…`));progress('Fetching 14-day Black Market volume…');const hist=await fetchHistory(state.settings.server,products,14,(d,t)=>progress(`History ${d}/${t} batches…`));const lookup=buildPriceLookup([...bm,...mats],state.overrides),vol=buildVolumeMap(hist),bmMap=new Map(bm.map(x=>[x.item_id,x]));state.results=items.map(recipe=>evaluateItem({recipe,settings:state.settings,priceLookup:lookup.get,bmRecord:bmMap.get(recipe.id),volume:vol.get(recipe.id)||0,overrideLookup:lookup.override})).filter(Boolean);state.updated=new Date;state.status=`Analyzed ${state.results.length} marketable recipes from ${items.length} candidates.`}catch(e){console.error(e);state.error=e.message||String(e);state.status='Scan failed.'}finally{state.scanning=false;render()}}

const header=()=>`<header class="topbar"><div class="brand"><b>SF</b><div><strong>Silverflow</strong><small>Albion Black Market Intelligence</small></div></div><div class="segments">${Object.entries(SERVERS).map(([k,v])=>`<button data-server="${k}" class="${state.settings.server===k?'on':''}">${v.label}</button>`).join('')}</div><div class="topfields"><label>Wallet <input id="wallet" type="number" value="${state.settings.wallet}"></label><label>Budget <input id="budget" type="number" value="${state.settings.budget}"></label><label class="switch"><input id="premium" type="checkbox" ${state.settings.premium?'checked':''}> Premium</label><button class="primary" id="scan" ${state.scanning?'disabled':''}>${state.scanning?'Scanning…':'Refresh scan'}</button></div></header>`;
const nav=()=>`<nav>${[['scanner','Scanner'],['favorites','Favorites'],['movers','BM Movers'],['settings','Settings']].map(([k,n])=>`<button data-tab="${k}" class="${state.tab===k?'on':''}">${n}${k==='favorites'?` <i>${state.favorites.size}</i>`:''}</button>`).join('')}</nav>`;
const summary=a=>`<section class="summary">${[['Visible',a.length],['Profitable',a.filter(r=>scenario(r)?.profit>0).length],['Best profit',a.length?fmtSilver(Math.max(...a.map(r=>scenario(r)?.profit||0))):'—'],['Best ROI',a.length?fmtPct(Math.max(...a.map(r=>scenario(r)?.roi||0))):'—'],['Catalog',`${state.catalog.length}${state.catalogSource==='seed'?' seed':''}`],['Updated',state.updated?state.updated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</section>`;
const filters=()=>{const s=state.settings;return `<section class="panel filters"><label>Tier<select id="tier"><option value="all">All</option>${[4,5,6,7,8].map(x=>`<option ${+s.tier===x?'selected':''}>${x}</option>`).join('')}</select></label><fieldset><legend>Enchant</legend>${[0,1,2,3,4].map(x=>`<label><input data-enchant="${x}" type="checkbox" ${s.enchants.includes(x)?'checked':''}>.${x}</label>`).join('')}</fieldset><label>Category<select id="category"><option value="all">All</option>${categories().map(x=>`<option ${s.category===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Buy materials<select id="acq"><option value="instant" ${s.acquisitionMode==='instant'?'selected':''}>Instant buy</option><option value="order" ${s.acquisitionMode==='order'?'selected':''}>Buy order</option></select></label><label>BM exit<select id="sale"><option value="instant" ${s.saleMode==='instant'?'selected':''}>Sell now</option><option value="order" ${s.saleMode==='order'?'selected':''}>List order</option></select></label><label>Min profit<input id="minProfit" type="number" value="${s.minProfit}"></label><label>Min ROI %<input id="minRoi" type="number" value="${s.minRoi}"></label><label>Min vol/day<input id="minVol" type="number" value="${s.minVolume}"></label><label>Max age h<input id="age" type="number" value="${s.freshnessHours}"></label><label class="switch"><input id="afford" type="checkbox" ${s.affordableOnly?'checked':''}> 50-run affordable</label></section>`};
const pair=(a,b)=>`<strong>${a?fmtSilver(a.profit):'—'}</strong><small>Focus ${b?fmtSilver(b.profit):'—'}</small>`;
const table=a=>a.length?`<div class="panel table"><table><thead><tr><th></th><th data-sort="name">Item</th><th data-sort="volume">BM/day</th><th data-sort="royal">Best Royal<br><small>No focus / Focus</small></th><th data-sort="caer">Caerleon<br><small>No focus / Focus</small></th><th data-sort="roi">ROI</th><th data-sort="capital">Capital ×50</th><th data-sort="profit">Profit ×50</th><th data-sort="age">Age</th><th></th></tr></thead><tbody>${a.map(row).join('')}</tbody></table></div>`:`<div class="panel empty">No opportunities pass the current budget, freshness, liquidity and profit filters.</div>`;
function row(r){const b=r.modes.baseline,f=r.modes.focus,p=scenario(r),fav=state.favorites.has(r.recipe.id);return `<tr><td><button class="star ${fav?'on':''}" data-fav="${esc(r.recipe.id)}">${fav?'★':'☆'}</button></td><td class="item"><img src="${itemIcon(r.recipe.id)}"><div><b>${esc(r.recipe.name||humanizeId(r.recipe.id))}</b><small>${itemTierLabel(r.recipe)} · ${esc(r.recipe.id)}</small></div></td><td>${fmtVolume(r.primary?.volume||0)}</td><td class="${b.bestRoyal?.profit>=0?'pos':'neg'}"><em>${esc(b.bestRoyal?.city||'—')}</em>${pair(b.bestRoyal,f.bestRoyal)}</td><td class="${b.caerleon?.profit>=0?'pos':'neg'}">${pair(b.caerleon,f.caerleon)}</td><td>${fmtPct(p?.roi||0)}</td><td>${fmtSilver((p?.cashRequired||0)*50)}</td><td class="${p?.profit>=0?'pos':'neg'}">${fmtSilver((p?.profit||0)*50)}</td><td><span class="fresh ${p?.freshness.className||'missing'}">${p?.freshness.label||'Missing'}</span><small>${fmtAge(p?.worstAge)}</small></td><td><button class="ghost" data-open="${esc(r.recipe.id)}">Analyze</button></td></tr>`}
function scanner(){const a=rows(),title=state.tab==='favorites'?'Favorites':state.tab==='movers'?'Black Market Movers':'Opportunity Scanner';return `${summary(a)}${filters()}<div class="heading"><div><h1>${title}</h1><p>Royal-vs-Caerleon crafting economics ranked with liquidity and quote freshness.</p></div><span id="scan-status">${esc(state.status)}</span></div>${state.error?`<div class="error">${esc(state.error)}</div>`:''}${table(a)}`}

function settings(){const s=state.settings;return `<div class="settings"><section class="panel card"><h2>Calculation</h2><label>Station fee / item<input id="station" type="number" value="${s.stationFee}"></label><label>Extra production bonus %<input id="extra" type="number" value="${s.extraProductionBonus}"></label><label>Custom batch<input id="customQty" type="number" value="${s.customQuantity}"></label><div class="formula"><b>RRR</b><code>bonus / (1 + bonus)</code><small>Base +18%, specialty +15%, focus +59%. Non-returnable components are excluded.</small></div></section><section class="panel card wide"><h2>Manual price overrides</h2><p>Server-specific. Use sell side for instant material buys / BM listings; buy side for material buy orders / BM sell-now.</p><div class="override"><input id="ovItem" placeholder="T4_SHOES_CLOTH_KEEPER@2"><select id="ovCity">${[...ALL_CRAFT_CITIES,BLACK_MARKET].map(x=>`<option>${x}</option>`).join('')}</select><select id="ovSide"><option value="sell">sell</option><option value="buy">buy</option></select><input id="ovPrice" type="number" placeholder="price"><button id="addOv" class="primary">Add</button></div>${state.overrides.map((o,i)=>`<div class="ovrow"><code>${esc(o.itemId)}</code><span>${SERVERS[o.server]?.label} · ${esc(o.city)} · ${o.side}</span><b>${fmtSilver(+o.price)}</b><button data-rm-ov="${i}" class="ghost">Remove</button></div>`).join('')||'<p class="muted">No overrides.</p>'}</section><section class="panel card"><h2>Data confidence</h2><p>Market observations are community-captured. Stale component or Black Market quotes are filtered using the maximum-age setting.</p><p>BM Movers uses 14-day average historical item count.</p><button id="reset" class="danger">Reset local settings</button></section></div>`}
function scenarioCard(name,x,focus){return x?`<div class="scard"><header><div><b>${name}</b><small>${focus?'Focus':'No focus'} · ${esc(x.city)}</small></div><strong class="${x.profit>=0?'pos':'neg'}">${fmtSilver(x.profit)}</strong></header><dl><div><dt>RRR</dt><dd>${fmtPct(x.rrr)}</dd></div><div><dt>Materials</dt><dd>${fmtSilver(x.grossMaterials)}</dd></div><div><dt>Returned</dt><dd>${fmtSilver(x.returnedValue)}</dd></div><div><dt>True craft</dt><dd>${fmtSilver(x.trueCraftCost)}</dd></div><div><dt>Net sale</dt><dd>${fmtSilver(x.netSale)}</dd></div><div><dt>ROI</dt><dd>${fmtPct(x.roi)}</dd></div></dl></div>`:`<div class="scard muted">No complete quote.</div>`}
function drawer(){const r=state.selected;if(!r)return'';const b=r.modes.baseline,f=r.modes.focus,p=scenario(r),qs=[50,100,+state.settings.customQuantity];return `<div class="shade" data-close></div><aside class="drawer"><button data-close class="x">×</button><div class="dhead"><img src="${itemIcon(r.recipe.id)}"><div><small>${itemTierLabel(r.recipe)} · ${esc(r.recipe.category)}</small><h2>${esc(r.recipe.name||humanizeId(r.recipe.id))}</h2><code>${esc(r.recipe.id)}</code></div></div><div class="meta">BM ${fmtVolume(r.primary?.volume||0)}/day · specialty ${esc(r.recipe.bonusCity||'none')} · quote <span class="fresh ${p?.freshness.className}">${p?.freshness.label}</span></div><h3>Production comparison</h3><div class="scenarios">${scenarioCard('Best Royal',b.bestRoyal,false)}${scenarioCard('Best Royal',f.bestRoyal,true)}${scenarioCard('Caerleon',b.caerleon,false)}${scenarioCard('Caerleon',f.caerleon,true)}</div><h3>Preferred baseline batches</h3><div class="batches">${qs.map(q=>{const m=batchMetrics(p,q);return m?`<div><b>×${q}</b><span>Capital ${fmtSilver(m.capital)}</span><span>True cost ${fmtSilver(m.trueCost)}</span><strong class="${m.profit>=0?'pos':'neg'}">Profit ${fmtSilver(m.profit)}</strong></div>`:''}).join('')}</div><h3>Component economics · ${esc(p?.city||'')}</h3><div class="materials">${(p?.materials||[]).map(m=>`<div><span><code>${esc(m.id)}</code><small>${humanizeId(m.id)}</small></span><span>×${m.count}</span><span>${fmtSilver(m.unitPrice)}</span><span>${m.returnable?'returnable':'fixed'}</span></div>`).join('')}</div><div class="math"><span>Gross materials <b>${fmtSilver(p?.grossMaterials||0)}</b></span><span>Returned value <b class="pos">−${fmtSilver(p?.returnedValue||0)}</b></span><span>Station + fixed <b>${fmtSilver((p?.station||0)+(p?.flatSilver||0))}</b></span><span>True craft cost <b>${fmtSilver(p?.trueCraftCost||0)}</b></span><span>Cash required <b>${fmtSilver(p?.cashRequired||0)}</b></span></div></aside>`}

function render(){app.innerHTML=`${header()}${nav()}<main>${state.tab==='settings'?settings():scanner()}</main><footer><span>Silverflow v1 · personal-use crafting intelligence</span><span>Market data: Albion Online Data Project</span></footer>${drawer()}`;bind()}
function bind(){
  $$('[data-server]').forEach(x=>x.onclick=()=>{save('server',x.dataset.server);scan()});$$('[data-tab]').forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;state.selected=null;render()});$('#scan')?.addEventListener('click',scan);
  $('#premium')?.addEventListener('change',e=>{save('premium',e.target.checked);scan()});$('#wallet')?.addEventListener('change',e=>{save('wallet',+e.target.value);render()});$('#budget')?.addEventListener('change',e=>{save('budget',+e.target.value);render()});
  $('#tier')?.addEventListener('change',e=>{save('tier',e.target.value==='all'?'all':+e.target.value);scan()});$('#category')?.addEventListener('change',e=>{save('category',e.target.value);scan()});$('#acq')?.addEventListener('change',e=>{save('acquisitionMode',e.target.value);scan()});$('#sale')?.addEventListener('change',e=>{save('saleMode',e.target.value);scan()});
  [['#minProfit','minProfit'],['#minRoi','minRoi'],['#minVol','minVolume'],['#age','freshnessHours']].forEach(([id,k])=>$(id)?.addEventListener('change',e=>{save(k,+e.target.value);render()}));$('#afford')?.addEventListener('change',e=>{save('affordableOnly',e.target.checked);render()});
  $$('[data-enchant]').forEach(x=>x.onchange=()=>{save('enchants',$$('[data-enchant]:checked').map(e=>+e.dataset.enchant));scan()});$$('[data-sort]').forEach(x=>x.onclick=()=>{const k=x.dataset.sort;state.sort=[k,state.sort[0]===k&&state.sort[1]==='desc'?'asc':'desc'];render()});
  $$('[data-fav]').forEach(x=>x.onclick=()=>{const id=x.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveFavorites(state.favorites);render()});$$('[data-open]').forEach(x=>x.onclick=()=>{state.selected=state.results.find(r=>r.recipe.id===x.dataset.open)||null;render()});$$('[data-close]').forEach(x=>x.onclick=()=>{state.selected=null;render()});
  $('#station')?.addEventListener('change',e=>save('stationFee',+e.target.value));$('#extra')?.addEventListener('change',e=>save('extraProductionBonus',+e.target.value));$('#customQty')?.addEventListener('change',e=>save('customQuantity',+e.target.value));
  $('#addOv')?.addEventListener('click',()=>{const itemId=$('#ovItem').value.trim(),price=+$('#ovPrice').value;if(!itemId||!price)return;state.overrides.push({server:state.settings.server,itemId,city:$('#ovCity').value,side:$('#ovSide').value,price});saveOverrides(state.overrides);render()});$$('[data-rm-ov]').forEach(x=>x.onclick=()=>{state.overrides.splice(+x.dataset.rmOv,1);saveOverrides(state.overrides);render()});$('#reset')?.addEventListener('click',()=>{state.settings={...DEFAULT_SETTINGS};state.overrides=[];saveSettings(state.settings);saveOverrides([]);render()});
}
async function boot(){render();try{const c=await loadCatalog();state.catalog=c.items;state.catalogSource=c.source;state.status=`Loaded ${c.items.length} recipes.`;await scan()}catch(e){state.error=e.message;state.status='Catalog load failed.';render()}}boot();
